travis:
  secure:
    BINSTAR_TOKEN: ZXXD2+RyLY2o/OSS3OE8cPK9AIw6athXMc2bKJr/sxObcii14FyiQULdnHw12f8YbMAV/FaTfn69wGteCbdz2PmYuU3c3R/pFsUuBAUNkaKz/8fiX0cgAsTRObIlinOsj9s+LV65J5UrDnxrHDlhytFLtYhbDC3xkrlqykxtZtPpFdG94Grl3g51mab1bbiu8LDRX70s5vZfA/mBaMsxfrovCZuIU2lf2gNo4SU8wwma35kXbxxwuws7Gqhfcul/WsIvmYP20Qem5ntvbeV/LP2BC/k2KUK7/3ekJQPX0gw0RoAAe4CgEb4BFvMO60Ku4mzzmEbVwqivY7kyV2Mp0eXiXMU1GWUgUHL1aFjspEU/j/iozsE1srHtg533CQGV6ixc1Pv2Ck44d8u0FhLfqyavtl7gzvvMpyJwpAFKi67kYt2wmbAb/9bPeutoaNecIPlmCm5KY4RMOi/yZpeCU68xTY8TXr8lwAXWwcKSnqwpHnIJD8cdjdSEx4msxqrydRk+5lPPn8uFNmswXSPev6KAREx8YHHDK8Wpui3yujeVbr/1ke+VVvihPFbZRvoMPIkgc6GB7/GRMc2MUX5gmIJQHnpqUVujDtOln5D05xUUuwzqjrAEKvHQXvsrzmebMXt5GHNYEscguZjZARLBSKgVaWsW/EUP/H6uSyBVLHo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
