travis:
  secure:
    BINSTAR_TOKEN: RAGQmGxeOULtA+3/Euwk5iLqV7IoXO1TQscgK9K7Ia2SXBGMdZx66ZhEpW/g/yOuQktyg6ptuK2Cv/lHO4/EJ/MbZSWK94AqqnoiPlcaDfaGrBv9COV3RiCqtNpnoKyLsKlZWkNerkJqVRoRiAZdPrIxmIHbRkk8hJ3ZPhyrjjL2ebHDnzEvGNy6ubiJ+FAhkeM/PI+9rV1HdIdw1FNnrBsn0lvGch07SI+vqW2dbbql7k3JuC7N+ADciLi9xQLnKZ4BhU0wb7KBi3Ft5j6ocM6whwb6GmhOVp3b7njws4yK8t0TyzD7t2zdSCepq28bNwsq30DrWhrOSl2SoDbJKWv9PpucnfgrCkA5J5DfK+Iz6ZVZQh5xKdQKU8NRCyZH+Np3adiVWE4pY55ahxjAVPIq5lJSkoLNUX1Uqi6mHW7395M/wA7UjpY5v/wemc4vWimOkGJtEqrMHQ6ml8A8tESUNNVCETW8KXeszle2iFay0F5FmRtshr5ES6PsqTv598v+9obZGlyldkSaf/AvRLlwCooySUX5YycBlgANssvZdvsrB6dMd/Zog2hXKUg/CqJeRaOLPSTvSTxAcDHfSnmwO55UmMLcnVOtLZJNrGvb9TVSPCSflNKYsFO+8PAy0Qbk+3evmRZJDV4CYSUD44M9wGF7NkDKlaoZ5wUnlJA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
